### ISSUE TITLE
Broken Photography Icon

### ISSUE THREAD

**Issue by RewoundVHS** [StevenMonty/StevenMonty.github.io#2]
The icon for photography is broken on my end.
![2019-02-17-150937_1600x900_scrot](https://user-images.githubusercontent.com/23706925/52918667-a46d0680-32c7-11e9-86bb-2cc2b79e05de.png)

I was able to fix this by changing this line: `<i class="i fas fa-camera">` to `<i class="icon fa fa-camera">`

**Comment by StevenMonty** [comment]
thanks!
